// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfumpevizrilmnyloexj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJmdW1wZXZpenJpbG1ueWxvZXhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzgwMTYsImV4cCI6MjA1OTQ1NDAxNn0.PhxVZ3U0P0bio4dJDrQYo3zpuxW0U2u1MZGC4ESPS20";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);